### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by mariuswestgaard** [joshuabaker/react-seomatic#3]
Hi! We recently upgraded our react version to react 18, which this package currently does not support. 

npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.6.0 || ^17" from react-seomatic@1.0.4
npm ERR! node_modules/react-seomatic
npm ERR!   react-seomatic@"^1.0.4" from the root project

Do you have any plan to upgrade react version? Would be great, as it's really useful 👍

**Comment by joshuabaker** [comment]
I’ve bumped the version to include React 18 as a peer. Give it a try now and please close if it all works.

**Comment by mariuswestgaard** [comment]
Awesome! It did not work though. It seems there's missing a "|" (pipe) in the peerDependencies before v 18.

**Comment by joshuabaker** [comment]
Oh, that’s a stupid mistake. 🤦🏻 

I’ve published another patch.

**Comment by mariuswestgaard** [comment]
Hehe, it happens. Thanks! It works now.
